import Link from "next/link";
export const metadata = { title: "How to read this", description: "What a reading is, what the status words mean, when a reading is held back, and how every number links to its source." };

import { PageHeader } from "@/components/PageHeader";
import { argument, meta, skippedSources, sources } from "@/lib/data";
import { fmt } from "@/lib/format";

const TIERS: [string, string, string][] = [
  ["1", "benchmark", "Benchmark or independent evaluation (METR horizons, Epoch benchmarks)"],
  ["2", "model_release", "Model release details (system cards, technical reports)"],
  ["3", "product_behaviour", "Public product behaviour (list prices, usage data from a product)"],
  ["4", "official_filing", "Official filing or policy (SEC filings, government statistics, enacted law, regulator lists)"],
  ["5", "credible_reporting", "Credible reporting (Reuters, Bloomberg, FT, WSJ, CNBC, The Information)"],
  ["6", "published_analysis", "Published analysis with a transparent method (surveys, research notes, analyst baskets)"],
  ["7", "actor_statement", "Statement from an actor about itself (intentions and self-measurements, not outcomes)"],
];

export default function Methodology() {
  const card = argument().migration.scorecard;
  const t = card.method as unknown as { words: [number, string][]; min_coverage: number; min_coverage_label: string; confidence_floor: number; weights: Record<string, number>; weights_rationale: string; half_life_rationale: string; grade_quality_rationale: string; hatch_rationale: string; epoch_quarterly_rationale: string };
  const registry: [string | null, string | null][] = [...sources().map((x) => [x.attribution, x.license] as [string | null, string | null]), ...skippedSources().map((x) => [x.attribution, null] as [string | null, string | null])];
  const credits = [...new Map(registry.filter(([a]) => a) as [string, string | null][]).entries()].map(([a, l]) => (l && /CC BY/i.test(l) ? `${a} (${l})` : a));
  return (
    <div className="flex flex-col gap-16">
    <PageHeader eyebrow="Method" title="How to read this site" lede="Every number here is a reading of something slow-moving, scored against a rule written down in advance. This page explains the readings in plain terms first; the full reference follows." />

    <section aria-labelledby="read" className="prose-folio">
      <h2 id="read" className="sr-only">How to read this</h2>
      <p>A <strong>reading</strong> is a number with a date and a source: a line in a company&apos;s annual filing, a cell in a government survey, a score in a benchmark file. Every figure on the site is a link. Follow it and you reach the record it came from, with the page it was taken from, the day it was fetched and the exact text it was read out of.</p>
      <p>Each indicator is scored against ranges the site publishes and can change only in public, with a written reason. For how fast things spread, the <em>normal</em> range is usually the pace an earlier general-purpose technology such as electricity or the personal computer managed at the same age, or the measure&apos;s own long-run trend where it has one. The <em>fast</em> range is the pace that the most aggressive forecasts need; the usual reference is AI 2027, a scenario written in 2025 by Daniel Kokotajlo, a former OpenAI researcher, and colleagues, in which AI outruns human researchers within a few years. A reading in the normal range says <em>consistent with normal</em>, in the fast range <em>faster than normal</em>, below both <em>slower than normal</em>, and between the two <em>emerging</em>.</p>
      <p>For who keeps the money, the words describe a trend over the last few readings rather than a range: <em>concentrating</em> when profit or share is gathering in fewer hands or one layer, <em>dispersing</em> when it is spreading out, <em>stable</em> when the change is too small to count, and <em>unclear</em> when the readings disagree with each other.</p>
      <p>Some readings are <strong>held rather than scored</strong>. A reading within a twentieth of the line between two ranges, or one whose margin of error covers both, reads <em>emerging</em> until it moves clear. Several readings of one underlying survey count as one vote, however many publishers repeat it. A company&apos;s statement about its own plans, or its own measurement of itself, can never move a status past <em>emerging</em> on its own.</p>
      <p>Every source carries a <strong>grade</strong> from A to D. A is independent measurement, an audited filing or an official statistic. D is a company talking about itself, or a single source nobody has confirmed. The grade is shown on each indicator&apos;s page and decides how far that reading can move a conclusion.</p>
      <p><strong>Unmeasured</strong> and <strong>unpublished</strong> mean different things. Unmeasured means nothing on the site measures that stage yet. Unpublished means the idea is recorded but no trustworthy free series exists yet, or its source is not yet connected; the reason sits on the indicator&apos;s row.</p>
      <p>Colour carries meaning and never a verdict. Violet with ▲ means faster or concentrating; teal with ▼ means slower or dispersing. Faster is not better and concentrating is not worse; the words and the arrows are always there, so nothing depends on seeing the colour.</p>
      <p>The whole case these readings test is set out in <Link href="/argument">the argument</Link>. What follows is the reference: how evidence is graded, how the ranges are set, and what the site does not measure.</p>
    </section>

    <article className="prose-tight max-w-[68ch] flex flex-col gap-5 text-[17px] leading-[1.65]">
      <div className="eyebrow">The reference</div>
      <p>One tracker, two lenses. The diffusion lens follows Narayanan and Kapoor&apos;s <em>AI as Normal Technology</em>: five stages a technology passes through (the paper calls them stocks), a flow between each (valves), and normal and fast ranges with thresholds that would falsify the argument. The capture lens measures who keeps the surplus, layer by layer. They are the same question asked from two ends, so they share one data store, one indicator object and one discipline, adapted from the <a href="https://ai2027-tracker.com/methodology/" className="underline decoration-grid underline-offset-4">AI 2027 tracker</a>.</p>
      <H>Three layers, strictly separated</H>
      <p><strong>Observation</strong> (raw, sourced, dated) → <strong>Derived</strong> (a formula over observations, defined in the semantic layer) → <strong>Indicator</strong> (proxies, status, confidence, evidence, counterevidence). No derived number exists without a traceable path to observation ids, and the site never computes a number: every figure was exported with the ids behind it.</p>
      <H>Evidence tiers</H>
      <div className="overflow-x-auto"><table className="data w-full text-sm"><thead><tr><th scope="col">Tier</th><th scope="col">Name in the data</th><th scope="col">What it covers</th></tr></thead>
        <tbody>{TIERS.map(([n, key, what]) => <tr key={n}><td className="tabular-nums">{n}</td><td><code className="text-xs">{key}</code></td><td className="text-ink-2">{what}</td></tr>)}</tbody></table></div>
      <p>The tier is stored; the letter grade is derived for display. A = tier 1, or tier 4 audited or government statistics. B = tiers 2–3, tier 4 company statements (8-K), tier 6 with a transparent method. C = tier 5, or tier 6 estimates. D = tier 7 or single-source. Tier 7 evidence never moves a status above <em>emerging</em>. <em>Audited</em> is reserved for tier 4 and a 10-K; a run-rate reported by the press or by the company is never audited, whatever its tier.</p>
      <H>Status vocabularies</H>
      <p>Flow indicators (diffusion): consistent with normal · faster than normal · slower than normal · emerging · not yet measurable, each against a normal band, a fast band and an optional falsifying band with a written rationale. Capture indicators: concentrating · dispersing · stable · unclear, from a trend over N periods with a dead-band. Every indicator also carries a timing tag: <em>leading</em> (moves before capture shows in filings), <em>coincident</em> (moves with it) or <em>lagging</em> (confirms it after the fact). Predictions: confirmed · ahead · on track · behind · emerging · not yet testable. <em>Not yet measurable</em> means the thing cannot be measured yet; an indicator whose connector has not landed is simply unpublished.</p>
      <H>Bands</H>
      <p>Each diffusion indicator names the single series or derived metric its bands apply to (shown as &ldquo;applied to&rdquo; on the indicator page), a normal band anchored on the pace of an earlier general-purpose technology at the same age, a fast band anchored on the pace the AI 2027 scenario needs, and where one exists a falsifying threshold. The rationale is written next to the numbers. Bands change only through a reviewed pull request that states why; the evaluator never moves them.</p>
      <H>Confidence, 0–95, independent of status</H>
      <p>{meta().confidence_rubric.slice().reverse().map((b, i) => <span key={b.lo}>{i ? "; " : ""}<span className="num">{b.lo}–{b.hi}</span> {b.label}</span>)}.</p>
      <H id="framing">How we frame value capture</H>
      <p>The capture lens asks who keeps the value AI creates. Five ideas organise the reading, and none of them supplies a number. <strong>The value stick:</strong> a transaction creates value between what a buyer would pay and what a supplier would accept, and each firm keeps the slice it can defend against rivals, buyers and suppliers (Brandenburger and Stuart, 1996). <strong>Schumpeterian profits:</strong> innovators have kept only a small share of the surplus their innovations create, and most of it reaches users (Nordhaus, 2004). <strong>Complementary assets:</strong> when imitation is easy, the owners of distribution, manufacturing, data and customer relationships capture the profits rather than the inventor (Teece, 1986). <strong>Installation and deployment:</strong> a technological revolution&apos;s installation period, financed by speculative capital, ends in a turning point, after which the technology spreads through the wider economy (Perez, 2002). <strong>Kinds of rent:</strong> scarcity rents on a constrained input, scale and network rents, switching-cost rents and regulatory rents, which <Link href="/argument/migration" className="underline decoration-grid underline-offset-4">migrate as bottlenecks move</Link>. The Ask model is given the same framing and may use it to organise an answer, never as the source of a figure.</p>
      <H>Discipline, enforced in code</H>
      <ul className="list-disc pl-5">
        <li>Every observation carries a URL that resolved at ingestion, its HTTP status, a content hash, the retrieval time, the tier, an audited/company-stated/reported/estimated flag, the extraction method and the raw snippet.</li>
        <li>Figures quoted from documents enter through a manual connector that fetches the page and asserts the snippet is a verbatim substring of it. Nothing is typed into an indicator.</li>
        <li>No single-source status change unless the source is a benchmark, a model release or an official filing. Non-empty counterevidence before anything publishes.</li>
        <li>Status lives only in status events, each with a reason, evidence ids and an author. The changelog is generated from them. Observations are superseded, never deleted; disputed figures carry their dispute text everywhere they appear.</li>
        <li>The evaluator proposes; it writes its own reason only for a first reading inside a band, and a band crossing waits for a human. Bands and formulas change only through a reviewed pull request.</li>
        <li>Rebuilt nightly at 06:17 UTC into a pull request that merges itself when the consistency checks, the tests and the site build all pass on exactly what it built; a failure holds it for review. What merges that way was decided by a published rule: observations that passed their source&apos;s checks, and first readings inside a band. A band crossing still waits for a human-written reason, and the card says so meanwhile.</li>
        <li>Fetched HTML passes through a prompt-injection scrub; anything addressed to an AI agent is logged and never stored.</li>
      </ul>
      <H>Query layer</H>
      <p>The Ask button and the console on <Link href="/query" className="underline decoration-grid underline-offset-4">/query</Link> run against the same store the site is exported from, on a separate read-only service whose database cannot read files or the network and cannot see pending or superseded rows. A question goes to a model with nine tools: read-only SQL over the semantic layer, a metric lookup, an indicator lookup, status changes since a date, a keyword search over observation snippets and the public research notes, a one-off trend fit, the labour-tracker concordance, the crosswalk, and an entity lookup. Every number in an answer must be followed by the citation token of the record it came from; a post-check extracts the numbers and verifies each against that record&apos;s value, confidence bounds, band edges or verbatim snippet. Research notes found by search carry no citation, so a number found only in a note cannot pass. An answer that fails is revised once; if it still fails the question is asked afresh once, and otherwise the answer is shown as blocked with the unverified numbers marked. The service cannot write observations or statuses and has a daily spend cap. For each answer it keeps the time, outcome, cost, number of lookups, the ids of the records cited, the model and the prompt version, never the question or the answer, and the nightly copies those records into the repository.</p>
      <H>Weekly memo</H>
      <p>Each Monday a job assembles what changed since the last memo (status events, new observations by indicator, watchlist posts, staleness, the thesis monitor, and any crosswalk pair whose two sides moved in opposite directions) and asks a model to draft the memo and the two lens sentences under the same citation rule. If no key is configured or the check fails twice, the memo is the deterministic digest of the same facts. Either way it opens a pull request; merging it publishes the memo under <Link href="/memos" className="underline decoration-grid underline-offset-4">/memos</Link>. Nothing in a memo can move a status.</p>
      <H>X posts</H>
      <p>The tracker makes no request to X: its robots.txt disallows the embed endpoint, and the API is paid. A post by someone the tracker reads enters only when a page it already fetches carries the post&apos;s text (an article quoting it, or a static embed), with that page as the source, the text as the verbatim snippet and the X link taken from the page. Every post is tier 7 and recorded as a watchlist row; when a post points to a tier 1&ndash;6 artifact, the artifact is fetched and entered in its own right. Posts never move a status, and the site shows their text with a link, never X&apos;s script.</p>
      <H>Colour</H>
      <p>Three colours carry meaning and nothing else does. Violet and teal mark direction (faster or concentrating; slower or dispersing) and always ship with an icon and a word. Orange marks how tightly an input binds, darker for tighter. Nothing is red or green: fast is not good, and concentrating is not good.</p>
      <H>Credits</H>
      <p>Method after the <a href="https://ai2027-tracker.com/methodology/" className="underline decoration-grid underline-offset-4">AI 2027 tracker</a> (independent, not affiliated).</p>
      <p className="text-sm text-ink-2">Data credits, generated from the source registry: {credits.join("; ")}.</p>
      <H id="charts">How the charts read</H>
      <p>Series marks are one slate, at three lightnesses, told apart by labels and dashes; the colours are reserved for meaning: violet for faster and concentrating, teal for slower and dispersing, orange for how tightly an input binds. Text is always ink: a colour appears only on a mark, a glyph or a border. Colour never carries a verdict on its own, so every status also has an icon and a word, and no chart uses red and green. The three colours were checked together for colour-vision separation on the white chart ground, for normal, protan, deutan and tritan vision. Hatching marks what is not firmly known. On the capture charts that is an estimated layer, hatched rather than tinted. On the tightness scorecard every score already rests partly on estimates, which its grade says, so hatching there marks a score whose confidence is low. Every chart has one vertical scale, names its sources beneath it, and repeats its numbers as text: each one links to the row it came from, and each series has a table and a CSV.</p>
      <H id="tightness">Tightness scores</H>
      <p><Link href="/argument/migration" className="underline decoration-grid underline-offset-4">The migrating bottleneck</Link> scores twenty-three inputs to AI, from minerals to money, on how hard each is to get. The scale runs from nought to a hundred and is read in five words: {t.words.slice().reverse().map(([floor, w]) => `${w} from ${floor}`).join(", ")}. It belongs to that page only. It is a different thing from the speed ranges above, and it never moves an indicator&apos;s status.</p>
      <p><strong className="font-medium">Gauges.</strong> Each input is read by a few gauges. A gauge takes one figure from the store, such as how fast the supply of chip packaging is growing, and turns it into points on a scale set by hand: a list of readings and the points each is worth, with straight lines between them and a flat line beyond either end. A reading off the end of its scale is marked as such. An input&apos;s tightness is the average of its gauges&apos; points, weighted, shown as a whole number. Every scale, with the reasoning behind it, is listed below; they were set by judgement and change only in public, with a written reason.</p>
      <p><strong className="font-medium">No data, no score.</strong> A gauge is dropped when it has no reading or its reading is older than its age limit. An input is withheld, never shown at fifty, when none of its gauges has a usable reading, when the one it depends on is missing, or when less than {t.min_coverage_label} of its intended evidence is fed. Each withheld input says why, and the reasons are kept apart: nobody publishes a series; one is published and this site does not read it yet; the gauge available does not measure what it claims; or the readings are too old or too few today.</p>
      <p><strong className="font-medium">Confidence.</strong> Beside every score is a confidence from nought to a hundred. It is worked out, not set by hand, and so it differs from the confidence on indicator pages. It rests on three things, multiplied together, each raised to a weight:</p>
      <ul className="list-disc pl-5 flex flex-col gap-2">
        <li><strong className="font-medium">Coverage ({t.weights.coverage}).</strong> How much of the intended evidence has a usable reading.</li>
        <li><strong className="font-medium">Freshness ({t.weights.freshness}).</strong> {t.half_life_rationale}</li>
        <li><strong className="font-medium">Source ({t.weights.source}).</strong> {t.grade_quality_rationale}</li>
      </ul>
      <p>{t.weights_rationale}</p>
      <p>The result cannot exceed the input&apos;s ceiling, which is set by hand and explained below. {t.hatch_rationale} A score whose confidence fell under {t.confidence_floor} would be withheld. Most of these gauges share one source, so their confidence moves together, and a gap of under ten points between two inputs means nothing.</p>
      <p><strong className="font-medium">Age limits.</strong> {t.epoch_quarterly_rationale}</p>
      <details className="text-sm">
        <summary className="cursor-pointer text-ink-2 hover:text-ink">Every gauge, its scale and the reasoning</summary>
        <div className="mt-3 flex flex-col gap-4">
          {card.inputs.filter((i) => i.gauges.some((g) => g.knots)).map((i) => (
            <section key={i.id}>
              <h3 className="font-medium text-ink">{i.name} <span className="font-normal text-muted">· ceiling {i.ceiling}</span></h3>
              <p className="text-ink-2">{i.ceiling_rationale}</p>
              {i.gauges.filter((g) => g.knots).map((g) => (
                <div key={g.id} className="mt-2 border-l border-grid pl-3">
                  <p className="text-ink">{g.label} <span className="text-muted">· weight {g.weight} · age limit {g.max_age_days} days{g.required ? " · required" : ""}</span></p>
                  <p className="num text-xs text-ink-2">{g.knots!.map(([x, pts]) => `${fmt(x, g.unit ?? undefined)} → ${pts}`).join(" · ")}{g.log10 ? "   (read on a multiplying scale)" : ""}</p>
                  <p className="text-ink-2">{g.scale_rationale}</p>
                </div>
              ))}
            </section>
          ))}
        </div>
      </details>
      <H id="map">The bottleneck map</H>
      <p><Link href="/bottlenecks" className="underline decoration-grid underline-offset-4">The bottleneck map</Link> lays the chain of inputs AI is made from, and the frictions Arvind Narayanan and Sayash Kapoor describe beyond it, against the stages of diffusion. On that page a bottleneck is whatever sets the pace, a scarce input upstream or a slow institution downstream. Each row prints today&apos;s reading once: an input&apos;s tightness score, or, for a friction, how many of its published indicators read faster than normal, normal or neither. A cell carries marks, never a colour: the row acts on that stage; nothing this site reads measures it; a named writer, or this site, expects it to bind there, one mark each. A claim about what happens on a row that does not say the row will bind, such as who gains or loses, is listed under the row and marks no cell. Where a stage is this site&apos;s placement rather than the author&apos;s, the cell says so.</p>
      <H id="signposts">Signposts</H>
      <p>Some readings are dated records of what AI can do, such as the best score on each capability test, or how fast agents grow more accurate against how fast they grow more reliable. They carry no faster-or-slower status, because nobody has yet defended a normal pace for them. They are tested only through the claims on the outlook page.</p>
      <H id="outlook">Claims about what happens next</H>
      <p><Link href="/outlook" className="underline decoration-grid underline-offset-4">What happens from here</Link> sets out named writers&apos; positions on the questions the outlook turns on. Each position names who holds it, or says it is this site&apos;s own, or this site carrying an author&apos;s argument further than they did, and each names a rival position. Each claim is tested every night against one reading and one line. It is holding when the reading meets the line, failing its test when it does not, and can&apos;t be tested yet when there is no reading, the reading is too old, or the claim is about reaching a line by a date that has not come. When the rival position expects the same reading, the claim reads &ldquo;both sides expect this&rdquo; instead of counting as a win for either side. A claim never changes an indicator&apos;s status. The <Link href="/predictions" className="underline decoration-grid underline-offset-4">predictions ledger</Link>, which scores dated forecasts people made in their own words, is kept apart.</p>
      <H id="singularity">Forecasts on the singularity timeline</H>
      <p><Link href="/singularity" className="underline decoration-grid underline-offset-4">The singularity timeline</Link> places dated forecasts of AI milestones, from essays of the 1960s to this year&apos;s revisions, on one row per milestone. Each forecast is a prediction in the ledger, written in this site&apos;s words, credited to its author and linked to its source; a book is reworded and credited, and a public work may carry one short exact quote. A mark sits at the year forecast: the most likely year where one was stated, otherwise the last year of the window, with a bar for a stated range; when it was said shows on hover, in the table and through the year slider. Calls that give only odds, or that bet against a date, are listed, not placed, and a claim about a step toward a milestone is drawn lighter and kept out of the forecaster table. The axis squeezes the decades before 2020 and after 2050 so the years around now get most of the width, and marks the places it changes.</p>
      <p>Each forecast carries one of the board&apos;s five words, from a status this site wrote with a reason: a window that has not opened reads too early to tell; a window that closed without the milestone reads slower than said; a forecaster&apos;s or a lab&apos;s own grade never settles one. Each milestone lists the readings this site takes that bear on it, and the four worlds for 2036 are read through the cells of the scenario grid, so a world reads consistent with tonight&apos;s readings until one of its signposts fails. Novels and stories sit on a last row, unscored: they are imagined futures, not forecasts.</p>
      <H id="atlas">The Singularity Atlas</H>
      <p><Link href="/singularity/atlas" className="underline decoration-grid underline-offset-4">The atlas</Link> gathers what named writers expect AI to change in eight parts of life, from money and work to health and an ordinary day. Each expectation is one writer&apos;s view in this site&apos;s words, credited and linked to a source this site has fetched, and placed by era (now and on the way, the first decade after AI can do most of what people do, and the long run) and by which of the four worlds it assumes; a view that holds whichever way things go counts in every world. They were drawn from the singularity canon by reading each work, and every line was checked against its source for who holds it, its conditions and its dates. Expectations are not scored and do not sit on the predictions board: most name no date and no test.</p>
      <p>The map counts sourced works, not writers and not odds: two lines from one work count once, and a darker cell means more works expect change there, never that change is more likely. The tint steps at fixed counts, so each world&apos;s map reads the same way. Beside each part of life sit the public series this site reads for it, each shown with the year of its latest reading, since several are annual; culture has none. The plates are illustrations made in v0, Vercel&apos;s AI design tool, for the site&apos;s owner in September 2026, recorded by the fingerprint of each original file; they illustrate and are not evidence.</p>
      <H id="census">The automatability census</H>
      <p>The automatability census asks which US knowledge work AI can take on today, task by task. It was built in a separate project from the Labor Department&apos;s list of the tasks in each occupation (O*NET), the Bureau of Labor Statistics&apos; wage bills by occupation and industry, and Anthropic&apos;s Economic Index of how people use its models. A task counts as able to go when someone can tell within hours whether it was done right, something other than a human expert can check it, a single mistake is cheap, and it needs no body. Up to three AI models scored each task and the verdict is their vote; no person judged individual tasks.</p>
      <p>This site imports each version of the census as published and never recomputes a verdict, share or range. It checks every file against the census&apos;s own list of fingerprints and that every table adds up to the same total, fetches every source a deal card links to, and loads the tables into the query console. Census figures are a judged snapshot, not observations, so they carry a reference to the file and row they come from instead of observation ids. Every total that can go appears beside the part all three models agree on; where one model never scored a task, the page says so rather than printing a zero. The census is structural, not a forecast: it says what can go under its rule, not when, how fast, or who keeps the saving, which it could not measure. Figures on repricing assume how easily one kind of work substitutes for another, so they are modelled and appear only in the census&apos;s method section.</p>
      <H id="reuse">Reuse, citation and corrections</H>
      <p>Code is MIT licensed. The operator&apos;s own contributions to the compiled dataset (observations as recorded, derived values, status events) are CC BY 4.0; each observation also carries its upstream source and licence, which govern that row, and third-party quotations, reworded source content and third-party selections are not covered (see <Link href="/legal#licences" className="underline decoration-grid underline-offset-4">the legal notice</Link>). Cite the site by URL and the observation ids you rely on. Corrections: open an issue or pull request on the repository; every change to a number or a status leaves a dated event in the changelog.</p>
      <H id="not-measured">Not measured, and why</H>
      <ul className="list-disc pl-5 flex flex-col gap-2">
        <li><strong className="font-medium">Return on capital against its cost, by layer.</strong> Invested capital is not filed by segment, the labs publish neither capital employed nor a cost of capital, and any cost of capital would be our assumption laid on theirs.</li>
        <li><strong className="font-medium">Markups.</strong> The marginal cost of a token is not public, and list prices are not transaction prices.</li>
        <li><strong className="font-medium">Abilities no public, dated test reads.</strong> Reasoning about cause and effect, memory that lasts from one session to the next, whether a model knows when it is wrong, how far training on generated data can go, whether models do what their makers intend, and sudden jumps in ability. The outlook makes no claim about them until a test does; the nearest readings are named where they exist, such as the predictability score inside the reliability index kept by HAL, Princeton&apos;s tracker of AI agents, and a benchmark of learning inside one task, which is not memory across sessions.</li>
        <li><strong className="font-medium">Anything that needs paid data.</strong> Lab and app gross margins, GPU rental prices, private valuations between rounds and market-wide round data are paywalled; each affected indicator says so on /indicators, and the paid sources are listed on /sources.</li>
      </ul>
      <H id="privacy">Privacy</H>
      <p>The site sets no cookies and stores nothing in your browser; what it and its hosts record is set out in <Link href="/legal#privacy" className="underline decoration-grid underline-offset-4">the privacy section of the legal notice</Link>.</p>
      <H id="disclaimers">Disclaimers</H>
      <p>Nothing here is advice, figures come without warranty, and parts of the site are written or judged by AI models: the terms are in <Link href="/legal" className="underline decoration-grid underline-offset-4">the legal notice</Link>. A status is an editorial judgement made under published rules: the maintainer chooses the bands and direction rules, writes down the rationale, and changes them only through a reviewed pull request.</p>
    </article>
    </div>
  );
}

function H({ children, id }: { children: React.ReactNode; id?: string }) { return <h2 id={id} className="display text-2xl leading-tight border-t border-grid pt-5 mt-2 scroll-mt-6">{children}</h2>; }
